export const CommonActions = {
  SAVE_ERROR_MESSAGE: "[COMMON] SAVE_ERROR_MESSAGE",
  SAVE_SUCCESS_MESSAGE: "[COMMON] SAVE_SUCCESS_MESSAGE",
  SAVE_PAGE_TITLE: "[COMMON] SAVE_PAGE_TITLE",
};

export const ThemeActions = {
  THEME_SET: "THEME_SET",
};

export const GatewayActions = {
  SAVE_GATEWAYS: "[GATEWAY] SAVE_GATEWAYS",
  ADD_GATEWAY: "[GATEWAY] ADD_GATEWAY",
  ADD_DEVICE: "[GATEWAY] ADD_DEVICE",
  REMOVE_DEVICE: "[GATEWAY] REMOVE_DEVICE",
};

export const UsersActions = {
  SAVE_USERS: "[USER] SAVE_USERS",
  SAVE_USER: "[USER] SAVE_USER",
  SAVE_SELECTED_USER: "[USER] SAVE_SELECTED_USER",
};

export const PostsActions = {
  SAVE_POSTS: "[POSTS] SAVE_POSTS",
  SAVE_POST: "[POSTS] SAVE_POST",
  SAVE_SELECTED_POST: "[POSTS] SAVE_SELECTED_POST",
  SAVE_COMMENTS: "[POSTS] SAVE_COMMENTS",
  SAVE_COMMENT: "[POSTS] SAVE_COMMENT",
};
