export const CommonActions = {
  SAVE_ERROR_MESSAGE: "[COMMON] SAVE_ERROR_MESSAGE",
  SAVE_SUCCESS_MESSAGE: "[COMMON] SAVE_SUCCESS_MESSAGE",
};

export const ThemeActions = {
  THEME_SET: "THEME_SET",
};

export const GatewayActions = {
  SAVE_GATEWAYS: "[GATEWAY] SAVE_GATEWAYS",
  ADD_GATEWAY: "[GATEWAY] ADD_GATEWAY",
  ADD_DEVICE: "[GATEWAY] ADD_DEVICE",
  REMOVE_DEVICE: "[GATEWAY] REMOVE_DEVICE",
};
